### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#2]
Hello @kiptoo 

the production build bumps errors. 

`$ yarn build` 

Please take a look. ty! 

*** *** *** *** 

![image](https://user-images.githubusercontent.com/51070104/205633249-507d7b53-67ad-41ef-9a1b-2b1a393df2c2.png)

**Comment by kiptoo** [comment]
sure, lemme take a look

**Comment by kiptoo** [comment]
I see where the issue is coming from, I have added the following links on the navbar whose documents I haven't migrated  yet 
- /content/tutorials
- /content/partners

once all document migration is done, this error will not throw

![buildError](https://user-images.githubusercontent.com/1720708/205637929-b5aacf8a-96d2-4391-85a2-8782f5b51f24.png)

**Comment by app-generator** [comment]
Cool. We can wait for the complete migration of the content.
Ty @kiptoo

**Comment by app-generator** [comment]
Validated. ty @kiptoo 
Closing.

**Comment by kiptoo** [comment]
fixed
