### ISSUE TITLE
404 Event - Not Triggered

### ISSUE THREAD

**Issue by app-generator** [app-generator/docs#9]
Hello @kiptoo 

Seems that the 404 event is not properly handled or is not active.
This case is not managed at DOCS level and seems to be handled by the hosting server. 

Please take a look. Ty! 

![image](https://user-images.githubusercontent.com/51070104/212464704-0eb79a1b-087d-411b-89d4-4ae5acaeac6b.png)

**Comment by kiptoo** [comment]
Hi @app-generator 
it looks like this issue is only on the production server, on local, it forces the defined 404.html

 ## This occurs when the error document defined in .htaccess is missing

Example:-
ErrorDocument 404 /404page.html


kindly check .htaccess of the server and set ErrorDocument  to

ErrorDocument 404 /404.html

**Comment by app-generator** [comment]
Seems to work. 
Ty @kiptoo
